import './global.css';
import { Roboto } from 'next/font/google';
import React from 'react';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children, ...props }: RootLayoutProps) {
  return (
    <html lang="en" className="antialiased">
      <body className={roboto.className}>
        {children}
        {/* <div className="grid min-h-screen ">
          {/* <SideBar />
          <main className="px-4 pb-12 pt-8">{children}</main>
        </div> */}
      </body>
    </html>
  );
}
