import './global.css';
import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { cn } from '@/lib/utils';
import { Roboto } from 'next/font/google';
import React from 'react';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface RootLayoutProps {
	children: React.ReactNode;
}

export default function RootLayout({ children, ...props }: RootLayoutProps) {
	return (
		<html lang="en" className="antialiased">
			<body className={cn('w-screen h-screen max-h-screen', roboto.className)}>
				<SidebarProvider>
					<AppSidebar />
					<main>
						<SidebarTrigger />
						{children}
					</main>
				</SidebarProvider>
			</body>
		</html>
	);
}
