import { ThemeProvider } from '@/components/theme-provider';
import './global.css';
import { AppSidebar } from '@/components/app-sidebar';
import {
	SidebarInset,
	SidebarProvider,
	SidebarTrigger,
} from '@/components/ui/sidebar';
import { cn } from '@/lib/utils';
import { Roboto } from 'next/font/google';
import React from 'react';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface RootLayoutProps {
	children: React.ReactNode;
}

export default function RootLayout({ children, ...props }: RootLayoutProps) {
	return (
		<html lang="en" className="antialiased" suppressHydrationWarning>
			<body className={cn('', roboto.className)} cz-shortcut-listen="true">
				<ThemeProvider attribute="class" defaultTheme="system">
					{/* <SidebarProvider>
						<AppSidebar />
						<SidebarInset> */}
					{/* <main className="max-h-screen"> */}
					{/* <SidebarTrigger /> */}
					{children}
					{/* </main> */}
					{/* </SidebarInset>
					</SidebarProvider> */}
				</ThemeProvider>
			</body>
		</html>
	);
}
